name: backend
description: An easily-extensible web server framework in Dart.
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: '>=2.0.0-dev <3.0.0'
homepage: https://github.com/angel-dart/angel
dependencies:
  angel_auth: ^2.0.0-alpha # Supports stateless authentication via JWT
  angel_configuration: ^2.0.0 # Loads application configuration, along with support for .env files.
  angel_file_service: ^2.0.0
  angel_framework: ^2.0.0-alpha # The core server library.
  angel_model: ^1.0.0
  angel_production: ^1.0.0-alpha
  angel_serialize: ^2.0.0
  angel_static: ^2.0.0-alpha # Static file server
  angel_validate: ^2.0.0-alpha # Allows for validation of input data
  pooled_map: ^1.0.0
  serverless:
    path: ../serverless
dev_dependencies:
  angel_hot: ^2.0.0 # Hot-reloading support. :)
  angel_serialize_generator: ^2.0.0
  angel_test: ^2.0.0-alpha # Utilities for testing Angel servers.
  build_runner: ^1.0.0
  io: ^0.3.2
  test: ^1.0.0
