name: serverless
publish_to: none
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_route: ^3.0.0
  json_annotation: ^1.0.0
  json_rpc_2: ^2.0.0
  stream_channel: ^1.0.0
dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^1.0.0